### PR TITLE
option to allow export of binary files stored in strl

### PR DESCRIPTION
**Pull request by JanMarvin**
This option allows to export binary data stored in a strl data.
[Stata.dta.zip](https://github.com/sjewo/readstata13/files/1995152/Stata.dta.zip)

```{R}
library(magrittr)
library(readstata13)

dd <- R.Version() %>%  data.frame()

dd %>% save.dta13(file = "~/dta-test/Rdata.dta", version = 14)
```

```{Stata}
/* binary example: https://www.stata.com/stata-news/news31-4/spotlight/ */


cd "~/dta-test"

use Rdata.dta, clear
generate strL notes = fileread("Rtest.txt")
generate strL image = fileread("Rlogo.png")
save "~/dta-test/Stata.dta", replace

browse 
```

```
setwd("/tmp")
dd <- read.dta13("~/dta-test/Stata.dta", strlexport = TRUE
```

### CODE REVIEW

**Comment by JanMarvin** [comment]
Some things could be improved
- This exports everything using our internal naming for the example file above: 15_1 and 16_1 and no file name is attached (I assume that Stata simply allows every file type, since we do not know, I leave it to the user to figure which file is which). We could use different names though e.g. variable names
- As shown in the example this exports everything, even perfectly normal strings. Maybe we could identify binaries and only export these and set replace.strl to FALSE for these.

**Comment by JanMarvin** [comment]
I assume the Travis builds failing are their faults. There is nothing in this PR that should cause problems in oldrel and stable (which I used)

**Comment by sjewo** [comment]
```
read_dta.cpp:550:56: error: no matching function for call to ‘std::basic_ofstream<char>::basic_ofstream(std::string&, std::_Ios_Openmode)’
       ofstream file1(outputpath, ios::out | ios::binary);
```
I saw this in the travis logs of R-Release. Maybe a outdated gcc?

**Comment by JanMarvin** [comment]
Thanks, did not see that in the logs: https://stackoverflow.com/a/28521615

Looks fine now.

**Comment by JanMarvin** [comment]
set.lang is now super fast. do we have a test for that?

**Pull request merged**
